/**
 * Poetic microcopy — centralized so the "禅" voice stays consistent.
 * (设置→调适, 收藏/书签→驻足, 删除→释怀, 导入→引卷, 文件夹导入→拾整卷,
 *  笔记→觉悟, 禅模式→禅境, 搜索→寻)
 */
export const COPY = {
  appName: '禅阅读',
  appNameLatin: 'ZenReader',
  appTitle: 'ZenReader · 禅阅读',
  tagline: '阅·见本心',

  library: '书库',
  import: '引卷',
  importFolder: '拾整卷',
  settings: '调适',
  bookmark: '驻足',
  delete: '释怀',
  note: '觉悟',
  zenMode: '禅境',
  fullscreen: '全屏',
  exitFullscreen: '退出全屏',
  search: '寻…',
  toc: '目录',
  notes: '觉悟笔记',

  emptyLibrary: '尚无书籍，静候墨香',
  emptyNotes: '尚无觉悟，静待花开',
  emptySearch: '寻无所获',

  selectionHighlight: '驻足',
  selectionNote: '写下觉悟',
  notePlaceholder: '用你自己的话，写下此刻所悟…',
  noteSearchPlaceholder: '寻原文与心得',
  newNote: '新建',
  editNote: '编辑',
  newInsight: '新写觉悟',
  editInsight: '重写觉悟',
  freeNote: '自由觉悟',
  deleteNote: '释怀此悟',
  deleteNoteHint: '此觉悟将随烟散去，不可复回。',
  save: '存',
  cancel: '罢',
  copyCode: '复制',
  copied: '已复制',
  backToTop: '回到卷首',
  shortcutTopBottom: '卷首 · 卷尾',

  words: '字',
  minutes: '分钟',

  resumeReading: '接着上次',
  readingProgress: '读到',
  finished: '已读毕',

  importDropHint: '引卷于此 —— 拖入 .md 文件',
  importFileAction: '引卷（选择文件）',
  importFolderAction: '拾整卷（选择文件夹）',
  importDone: '已引入',
  importSkipped: '已略过',
  importTo: '引入到',

  // 设置面板（调适）
  theme: '主题',
  themeLight: '明亮',
  themeSepia: '暮色',
  themeDark: '夜读',
  font: '字体',
  fontSerif: '衬线',
  fontSans: '无衬线',
  fontSize: '字号',
  lineHeight: '行距',
  textWidth: '页宽',
  paragraphIndent: '段首缩进',
  justify: '两端对齐',
  immersiveFullscreen: '沉浸全屏',
  immersiveFullscreenHint: '入禅境时自动进入全屏，出定一并退去；全屏本身不牵动禅境',
  zenEntry: '入定动画',
  zenEntryHint: '入禅境时的过场仪式，轻触任意处可跳过',
  zenEntryInk: '墨韵',
  zenEntryInkHint: '一滴墨坠入屏心，一笔圆相书就，三息呼吸里世界层层退去',
  zenEntryLeaf: '落叶',
  zenEntryLeafHint: '一叶知秋，风起万叶；暮色四合，万叶栖水，末叶点水澄明自现',
  zenEntryIncense: '香篆',
  zenEntryIncenseHint: '万点香尘洒落成一篆，火星循篆而行、烟起成书；篆尽烟敛，万缕归作一点澄明',
  zenEntryGalaxy: '星河',
  zenEntryGalaxyHint:
    '夜幕徐合，万点星尘旋成星河，随呼吸涨落；万点归一凝作一滴，坠入砚心，涟漪散尽澄明',
  zenEntryMist: '轻雾',
  zenEntryMistHint: '不设仪式，一口短雾拂过即入定',
  zenEntryRandom: '随机',
  zenEntryRandomHint: '每次入定在墨韵、落叶、香篆、星河之间随机择一',
  zenEntryPreview: '试播',
  paperTexture: '纸纹',
  paperTextureOff: '无',
  paperTextureSubtle: '微',
  paperTextureRich: '显',
  reading: '阅读',
  vaultFolder: '书库目录',
  chooseFolder: '选择文件夹',
  noFolder: '未设置',
  clearFolder: '清除',
  desktopOnly: '桌面端可用',

  openVault: '打开书库',
  refresh: '刷新',
  removeDoc: '移出书库',
  removeDocHint: '将释去此卷：本地文件、觉悟笔记与阅读进度一并放下，不可复回。',
  newFolder: '新建分组',
  folderName: '分组名',
  moveTo: '移到分组',
  moveToRoot: '根目录',
  moreActions: '更多操作',

  // 禅钟（歇息提醒）
  zenClock: '禅钟',
  reminderEnable: '开启',
  reminderInterval: '香长',
  reminderIntervalUnit: '分钟',
  reminderActions: '歇息之道',
  reminderPreHint: '燃香预提示',
  reminderPreHintHint: '香将尽时，香形由淡转显；关掉则燃香全程保持极淡',
  reminderChime: '香尽钟音',
  reminderChimeHint: '香燃尽时轻声颂钵音，禅境闭目亦可知',
  reminderPreset: '小憩',
  reminderPresetIncense: '一炷',
  reminderPresetDeep: '深读',
  reminderPresetLong: '长卷',
  incenseGone: '一炷香已尽',
  igniteHint: '点香 · 开始计时',
  trayIgnite: '点香',
  trayOpen: '打开主窗',
  trayQuit: '退出',
  trayIdle: '香未燃',
  litNotice: '香已点燃',
  snuff: '熄香',
  relight: '再燃一炷',
  burned: '已燃',
  breakStretch: '起身，散散步',
  breakWater: '饮口水',
  breakEyes: '望向远处，二十息',
  breakBreathe: '闭目，静静',
  restGuideStretch: '离开座位，走动片刻，松一松肩背',
  restGuideWater: '慢慢喝一杯水，不急',
  restGuideEyes: '望向六米外的远处，让眼睛歇一歇',
  restGuideBreathe: '随圆呼吸，吸四拍，呼六拍',
  restDone: '回来吧',
  breakKnow: '知晓',
  actStretch: '散行',
  actWater: '饮水',
  actEyes: '望远',
  actBreathe: '静息',
  remaining: '还剩',

  // 散落文案收编（此前硬编码于各视图）
  continueImport: '继续引卷',
  vaultNotOpen: '请先打开书库，方能引卷入藏',
  close: '关闭',
  escToReturn: '按 Esc 返回',
  zenInhale: '吸',
  zenExhale: '呼',
  zenSkipHint: '轻触任意处 · 跳过',
  emptyToc: '卷中尚无章节',
  emptyFolders: '尚无分组',

  // 导入状态流转
  importPending: '待引',
  importReading: '读卷中',
  importParsing: '解卷中',
  importSaving: '藏卷中',
  importStored: '已藏',
  importSkippedDup: '已略过 · 同名',
  importError: '有误',
  importDuplicateHint: '同名卷已在库中，故而略过',
  importUnknownError: '未知错误',

  // 操作反馈（轻提示）
  movedDone: '此卷已移妥',
  removedDone: '已释怀，此卷随烟散去',
  folderCreated: '分组已成',
  noteSaved: '觉悟已存',
  opFailed: '未能完成，请稍后再试',
  vaultReadFailed: '书库难以读取，请确认目录仍可访问',
  docOpenFailed: '未能打开此卷',
  anchorCrossBlock: '暂只支持一段之内驻足',

  // 加载态
  loadingDoc: '翻卷中…',
  loadingLibrary: '开卷中…',

  // 拖拽引卷
  dropToImport: '松手引卷入藏',

  // 键径（快捷键速查）
  shortcutSheet: '键径',
  shortcutDown: '向下徐行',
  shortcutUp: '向上回望',
  shortcutSpace: '翻过一页（Shift 回翻）',
  shortcutPrevChapter: '上一章',
  shortcutNextChapter: '下一章',
  shortcutToc: '目录开合',
  shortcutNotes: '觉悟笔记开合',
  shortcutZen: '禅境出入',
  shortcutEsc: '层层退返',
  shortcutFullscreen: '全屏切换',
  shortcutSheetKey: '键径',
} as const

export type CopyKey = keyof typeof COPY
