/**
 * Poetic microcopy — centralized so the "禅" voice stays consistent.
 * (设置→调适, 收藏/书签→驻足, 删除→释怀, 导入→引卷, 文件夹导入→拾整卷,
 *  笔记→觉悟, 禅模式→禅境, 搜索→寻)
 */
export const COPY = {
  appName: '禅阅读',
  appNameLatin: 'ZenReader',
  tagline: '阅·见本心',

  library: '书库',
  import: '引卷',
  importFolder: '拾整卷',
  settings: '调适',
  bookmark: '驻足',
  delete: '释怀',
  note: '觉悟',
  zenMode: '禅境',
  fullscreen: '全屏',
  exitFullscreen: '退出全屏',
  search: '寻',
  toc: '目录',
  notes: '觉悟笔记',

  emptyLibrary: '尚无书籍，静候墨香',
  emptyNotes: '尚无觉悟，静待花开',

  selectionHighlight: '驻足',
  selectionNote: '写下觉悟',
  notePlaceholder: '用你自己的话，写下此刻所悟…',
  save: '存',
  cancel: '罢',

  words: '字',
  minutes: '分',

  resumeReading: '接着上次',
  readingProgress: '读到',
  finished: '已读毕',

  importDropHint: '引卷于此 —— 拖入 .md 文件',
  importFileAction: '引卷（选择文件）',
  importFolderAction: '拾整卷（选择文件夹）',
  importDone: '已引入',
  importSkipped: '已略过',
  importTo: '引入到',

  // 设置面板（调适）
  theme: '主题',
  themeLight: '明亮',
  themeSepia: '暮色',
  themeDark: '夜读',
  font: '字体',
  fontSerif: '衬线',
  fontSans: '无衬线',
  fontSize: '字号',
  lineHeight: '行距',
  textWidth: '页宽',
  paragraphIndent: '段首缩进',
  justify: '两端对齐',
  immersiveFullscreen: '沉浸全屏',
  paperTexture: '纸纹',
  paperTextureOff: '无',
  paperTextureSubtle: '微',
  paperTextureRich: '显',
  reading: '阅读',
  vaultFolder: '书库目录',
  chooseFolder: '选择文件夹',
  noFolder: '未设置',
  clearFolder: '清除',
  desktopOnly: '桌面端可用',

  openVault: '打开书库',
  refresh: '刷新',
  removeDoc: '移出书库',
  removeDocHint: '将释去此卷：本地文件、觉悟笔记与阅读进度一并放下，不可复回。',
  newFolder: '新建分组',
  folderName: '分组名',
  moveTo: '移到分组',
  moveToRoot: '根目录',
  moreActions: '更多操作',

  // 禅钟（歇息提醒）
  zenClock: '禅钟',
  reminderEnable: '开启',
  reminderInterval: '香长',
  reminderIntervalUnit: '分钟',
  reminderActions: '歇息之道',
  reminderPreHint: '燃香预提示',
  reminderPreHintHint: '香将尽时，香形由淡转显；关掉则燃香全程保持极淡',
  reminderChime: '香尽钟音',
  reminderChimeHint: '香燃尽时轻声颂钵音，禅境闭目亦可知',
  reminderPreset: '小憩',
  reminderPresetIncense: '一炷',
  reminderPresetDeep: '深读',
  reminderPresetLong: '长卷',
  incenseGone: '一炷香已尽',
  igniteHint: '点香 · 开始计时',
  litNotice: '香已点燃',
  awayNotice: '离席片刻，香已熄',
  snuff: '熄香',
  relight: '再燃一炷',
  burned: '已燃',
  breakStretch: '起身，散散步',
  breakWater: '饮口水',
  breakEyes: '望向远处，二十息',
  breakBreathe: '闭目，静静',
  breakKnow: '知晓',
  actStretch: '散行',
  actWater: '饮水',
  actEyes: '望远',
  actBreathe: '静息',
  remaining: '还剩',
} as const

export type CopyKey = keyof typeof COPY
